services:
  - type: web
    name: trading-bot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn chartink-fyers-backend.main:app --host 0.0.0.0 --port 10000"

  - type: web
    name: trading-bot-frontend
    env: static
    buildCommand: "cd chartink-fyers-frontend && npm install && npm run build"
    staticPublishPath: "chartink-fyers-frontend/dist"
